apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-local
  namespace: kube-system
  labels:
    application: coredns
data:
  Corefile: |
    .:54 {
        errors
        health :9154
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            upstream
            fallthrough in-addr.arpa ip6.arpa
        }
{{ if eq .ConfigItems.enable_skipper_eastwest "true"}}
        template IN A ingress.cluster.local  {
            match "^.*[.]ingress[.]cluster[.]local"
            answer "{{"{{"}} .Name {{"}}"}} 60 IN A 10.3.99.99"
            fallthrough
        }
{{ end }}
        prometheus :9153
        proxy . /etc/resolv.conf
        pprof 127.0.0.1:9155
        cache 30
        reload
    }
