kind: Service
apiVersion: v1
metadata:
  name: coredns-local-dnsmasq
  namespace: kube-system
  labels:
    application: coredns
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "9054"
    prometheus.io/scrape: "true"
spec:
  selector:
    application: coredns
    instance: node-dns
  type: ClusterIP
  ports:
  - name: monitor
    port: 9054
    targetPort: 9054
    protocol: TCP
